### ISSUE TITLE
[Feature Request] Music Shuffle gives Ancient Cave shortcuts their own song

### ISSUE THREAD

**Issue by HermitDreams** [stochaztic/eb-randomizer#11]
Kinda like the Super Mario Bros 3 Warp Zone, I'd like it if shortcuts were treated as a "Level 10" in Ancient Cave, for the purpose of Music Shuffling giving them their own song and hiding where the entrances will take you.

**Comment by stochaztic** [comment]
An interesting idea; the main issue I see is not only the Monkey Cave rooms are shortcut rooms; so are PRV, south Scaraba, the Winters area where the Pencil Eraser is, and even all of central Onett due to the cliffside shack. I'm not sure there's a way to not mislead people that either these areas don't have skips or aren't part of a normal floor, when both are true, if this was in place.

**Comment by HermitDreams** [comment]
I would say only Monkey Caves, PRV, South Scaraba, and the room where you use the Tiny Ruby would be considered explicitly Warp Zones because without the shortcut, they're just dead ends.

**Comment by stochaztic** [comment]
Closed, decided not to implement this idea.
