### ISSUE TITLE
Softlock in v25 keysanity (Dr. Andonuts' Lab)

### ISSUE THREAD

**Issue by cpetosky** [stochaztic/eb-randomizer#2]
Hey, thanks for making this tool. I had a lot of fun for about two hours, and now I think I'm stuck.

Generation link: https://earthbound.app/?version=25&seed=65488344&flags=bcd3gim2npsuk

__Stuck state:__

I did the solo Jeff run through Winters and ended up at Andonuts lab. But instead of giving me the sky runner, he talks about visiting rainy circle -- which IIRC is what's supposed to happen when you come back later with Ness.

Visiting Rainy Circle naturally doesn't work with just Jeff, and so I think I'm stuck in the lab.

__Rough playthrough order__

1. Get Buzz Buzz and defeat Starman Jr.
2. Teleport with Buzz Buzz in party to Onett, beat Frank.
3. Talk to Mayor, receive pencil eraser.
4. Head to Twoson, go through Happy Happy Valley as encounters are still disabled at this point.
5. Talk to Paula in cell, encounters are now re-enabled.
6. Head back to Onett and let Buzz Buzz die, as he's now more harm than good.
7. Feed and fund Apple Kid. Head to pencil eraser statue (which is gone already per step 4) and back to Twoson.
8. Get receiver call as normal, but both orange kid and apple kid's houses are empty at this point. (possibly another bug if Pencil Eraser spot can be progression item?)
9. I fought Everdred in Burglin' Park somewhere around here. Also I headed back to attempt carpainter (no Franklin Badge, so kicked out) and beat Your Sanctuary 2.
10. Head to Summers to try to pick up Poo, but I don't see the Magic Cake vendor (sprite shuffle is on so maybe I missed her)
11. Head to Threed and trigger solo Jeff adventure, which I did as normal.

**Comment by stochaztic** [comment]
There is very probably a softlock here, but I did notice a couple things that might help you out:

1. After the receiver phone call, Apple Kid should be in Burglin Park, not his house.
1. To get the Magic Cake vendor to appear, you need to call the Stoic Club then talk to a couple people, including her, inside to get her to go outside.
1. Once that's done, the entire solo Jeff adventure should never be necessary.

Due to the large number of ways you can get the events to go, it's probably not possible to fully prevent Keysanity softlocks, but it would definitely be good to prevent common-ish ones like this, so I'll check it out. Keysanity hasn't gotten a lot of testing yet, so I appreciate the bug reports!

**Comment by cpetosky** [comment]
Thanks for the advice on the first two things. I was pretty sure I'd messed at least one of those up! That's what I get for jumping in a randomizer after not playing for 10 years, heh.
